magnum_gripper:
  # can_interface: "/dev/serial/by-id/usb-mjbots_fdcanusb_5B75C352-if00" # bottom left usbc on laptop
  can_interface: "can0" # bottom left usbc on laptop
  motor_id: 3
  pid_position:
    kp: 15.0
    ki: 0.0
    kd: 5
  min_pos: -0.35
  max_pos: 0.005
  max_vel: 0.01
  max_acc: 0.01
