magnum_gripper:
  can_interface: "/dev/serial/by-id/usb-mjbots_fdcanusb_C54FFEC3-if00"
  motor_id: 1
  pid_position:
    kp: 15.0
    ki: 0.0
    kd: 5
  min_pos: -0.35
  max_pos: 0.005
  max_vel: 0.01
  max_acc: 0.01
